name: Deploy Desafio 3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout no repositorio
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build SlnImc.sln

      - name: Test
        run: dotnet test SlnImc.sln

      - name: Publish
        run: dotnet publish -c Release -o dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: ft-deploy
          folder: ./dist
          token: ${{ secrets.GITHUB_TOKEN }}
